// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Pick {
  _id?: { $oid: string };
  userId: string;
  teamId: string;
  weekId: string;
  leagueId: string;
}
